Repository ouster-lidar/ouster-ros, pull requests merged in 2023-08, with the labels that each got.

#188 SW-5396: publish point cloud in destaggered form
  CHANGELOG.rst
  include/ouster_ros/os_ros.h
  package.xml
  src/imu_packet_handler.h
  src/lidar_packet_handler.h
  src/os_image_nodelet.cpp
  src/os_ros.cpp
  src/point_cloud_processor.h
Labels: enhancement

#187 SW-5396: publish point cloud in destaggered form (foxy)
  CHANGELOG.rst
  ouster-ros/config/viz-reliable.rviz
  ouster-ros/include/ouster_ros/os_ros.h
  ouster-ros/launch/record.independent.launch.xml
  ouster-ros/launch/replay.independent.launch.xml
  ouster-ros/package.xml
  ouster-ros/src/imu_packet_handler.h
  ouster-ros/src/laser_scan_processor.h
  ouster-ros/src/lidar_packet_handler.h
  ouster-ros/src/os_image_node.cpp
  ouster-ros/src/os_ros.cpp
  ouster-ros/src/point_cloud_processor.h
  ouster-ros/src/thread_safe_ring_buffer.h
Labels: enhancement

#189 Add tf_prefix to point_cloud_frame
  src/os_transforms_broadcaster.h
Labels: bug, enhancement

#199 Destagger timestamp of each point as well
  src/os_ros.cpp
Labels: bug

#194 SW-5459: add a parameter for utc/tai time offset
  CHANGELOG.rst
  Dockerfile
  README.md
  include/ouster_ros/os_ros.h
  launch/common.launch
  launch/driver.launch
  launch/record.launch
  launch/replay.launch
  launch/sensor.launch
  launch/sensor_mtp.launch
  package.xml
  src/imu_packet_handler.h
  src/lidar_packet_handler.h
  src/os_cloud_nodelet.cpp
  src/os_driver_nodelet.cpp
  src/os_ros.cpp
  src/os_sensor_nodelet_base.cpp
  src/os_transforms_broadcaster.h
  src/point_cloud_processor.h
Labels: enhancement

#195 SW-5459: add a parameter for utc/tai time offset
  CHANGELOG.rst
  Dockerfile
  LICENSE
  README.md
  ouster-ros/config/driver_params.yaml
  ouster-ros/config/os_sensor_cloud_image_params.yaml
  ouster-ros/include/ouster_ros/os_ros.h
  ouster-ros/launch/record.composite.launch.xml
  ouster-ros/launch/replay.composite.launch.xml
  ouster-ros/launch/sensor.composite.launch.xml
  ouster-ros/launch/sensor.independent.launch.xml
  ouster-ros/launch/sensor_mtp.launch.xml
  ouster-ros/package.xml
  ouster-ros/src/image_processor.h
  ouster-ros/src/imu_packet_handler.h
  ouster-ros/src/laser_scan_processor.h
  ouster-ros/src/lidar_packet_handler.h
  ouster-ros/src/os_cloud_node.cpp
  ouster-ros/src/os_driver_node.cpp
  ouster-ros/src/os_replay_node.cpp
  ouster-ros/src/os_ros.cpp
  ouster-ros/src/os_sensor_node.cpp
  ouster-ros/src/os_sensor_node.h
  ouster-ros/src/os_sensor_node_base.cpp
  ouster-ros/src/os_static_transforms_broadcaster.h
  ouster-ros/src/point_cloud_processor.h
  ouster-ros/src/thread_safe_ring_buffer.h
Labels: enhancement

#198 SW-5459: add a parameter for utc/tai time offset
  CHANGELOG.rst
  Dockerfile
  LICENSE
  README.md
  ouster-ros/config/driver_params.yaml
  ouster-ros/config/os_sensor_cloud_image_params.yaml
  ouster-ros/include/ouster_ros/os_ros.h
  ouster-ros/launch/record.independent.launch.xml
  ouster-ros/launch/replay.independent.launch.xml
  ouster-ros/launch/sensor.composite.launch.xml
  ouster-ros/launch/sensor.independent.launch.xml
  ouster-ros/launch/sensor_mtp.launch.xml
  ouster-ros/package.xml
  ouster-ros/src/image_processor.h
  ouster-ros/src/imu_packet_handler.h
  ouster-ros/src/laser_scan_processor.h
  ouster-ros/src/lidar_packet_handler.h
  ouster-ros/src/os_cloud_node.cpp
  ouster-ros/src/os_driver_node.cpp
  ouster-ros/src/os_replay_node.cpp
  ouster-ros/src/os_ros.cpp
  ouster-ros/src/os_sensor_node.cpp
  ouster-ros/src/os_sensor_node.h
  ouster-ros/src/os_sensor_node_base.cpp
  ouster-ros/src/os_static_transforms_broadcaster.h
  ouster-ros/src/point_cloud_processor.h
Labels: enhancement
